### ISSUE TITLE
unclear validation for yearly files

### ISSUE THREAD

**Issue by oloapinivad** [PRIMAVERA-H2020/primavera-val#16]
Hi Jon,

I am testing the validation script with monthly cmorized data that have been merged into yearly files using NCO. However, even if the files seems ok, the validation tool - which it works perfectly on the single monthly files - reports time dimension inconsistency. 
However, manual inspection suggests that everything is fine. Did you ever seen something like that?

Thanks a lot for any help!

```
(validate) [pdavini0@r000u06l01 Year_1950_NCO]$ /marconi_work/IscrB_DIXIT/ecearth3/cmorization/primavera-val/bin/validate_data.py -s rldscs_Amon_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195001-195012.nc
/marconi_work/IscrB_DIXIT/opt/anaconda2/envs/validate/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/marconi_work/IscrB_DIXIT/opt/anaconda2/envs/validate/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
WARNING: File failed validation:
The points in the time dimension in the file are not contiguous: rldscs_Amon_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195001-195012.nc
ERROR: 1 files failed validation
(validate) [pdavini0@r000u06l01 Year_1950_NCO]$ cdo info rldscs_Amon_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195001-195012.nc
    -1 :       Date     Time   Level Gridsize    Miss :     Minimum        Mean     Maximum : Parameter ID
     1 : 1950-01-16 12:00:00       0   131072       0 :      32.168      260.07      452.62 : -1            
     2 : 1950-02-15 00:00:00       0   131072       0 :      57.797      259.70      451.82 : -1            
     3 : 1950-03-16 12:00:00       0   131072       0 :      56.102      259.96      435.76 : -1            
     4 : 1950-04-16 00:00:00       0   131072       0 :      31.353      263.37      443.76 : -1            
     5 : 1950-05-16 12:00:00       0   131072       0 :      30.210      270.96      446.55 : -1            
     6 : 1950-06-16 00:00:00       0   131072       0 :      40.631      278.94      454.33 : -1            
     7 : 1950-07-16 12:00:00       0   131072       0 :      30.421      281.32      498.45 : -1            
     8 : 1950-08-16 12:00:00       0   131072       0 :      30.593      281.16      486.36 : -1            
     9 : 1950-09-16 00:00:00       0   131072       0 :      23.926      272.30      462.63 : -1            
    10 : 1950-10-16 12:00:00       0   131072       0 :      45.330      265.33      440.96 : -1            
    11 : 1950-11-16 00:00:00       0   131072       0 :      9.7350      261.43      440.33 : -1            
    12 : 1950-12-16 12:00:00       0   131072       0 :      37.959      260.64      425.64 : -1            
cdo info: Processed 1572864 values from 1 variable over 12 timesteps ( 0.13s )

**Comment by jonseddon** [comment]
The failing check is using https://scitools.org.uk/iris/docs/latest/iris/iris/coords.html?highlight=is_contiguous#iris.coords.AuxCoord.is_contiguous

The times in each of those months is varying between midday and midnight. Is there a discontinuity in the bounds because of this?

Could you upload a sample failing file to JASMIN or somewhere else that I can access it please? Please email me with the path to the uploaded file if that's easiest.

**Comment by oloapinivad** [comment]
Hi Jon,
it was simpler to compress and upload it here, it is a small file.
The time is varying because - as long as I understand - these are monthly average so that the length of the month is affecting the averaged time value. I used NCO 4.6.4

When I check ncdump -h of the original file and the present they present actually the same metadata but the time length, so I cannot exactly understand what's happening.

[rldscs_Amon_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195001-195012.nc.zip](https://github.com/PRIMAVERA-H2020/primavera-val/files/2397624/rldscs_Amon_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195001-195012.nc.zip)

**Comment by jonseddon** [comment]
Hi Paolo,

Thanks for the file. The bounds have not been set correctly for each month:

```
$ ncdump  -v time_bnds rldscs_Amon_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195001-195012.nc
data:

 time_bnds =
  0, 31,
  0, 28,
  0, 31,
  0, 30,
  0, 31,
  0, 30,
  0, 31,
  0, 31,
  0, 30,
  0, 31,
  0, 30,
  0, 31 ;

$ ncdump  -v time rldscs_Amon_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195001-195012.nc

data:

 time = 15.5, 45, 74.5, 105, 135.5, 166, 196.5, 227.5, 258, 288.5, 319, 349.5 ;

```

The contiguity check is based on these bounds and so is failing at the moment.

Thanks,

Jon

**Comment by oloapinivad** [comment]
Hi Jon,

Sorry for but I am a bit confused - I am new of in these things. These files have been produced from the merging with NCO of single monthly files, which each reads as expected:

```
$ ncdump  -v time_bnds rldscs_Amon_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195001-195001.nc
 time_bnds =
  0, 31 ;
$ ncdump  -v time rldscs_Amon_EC-Earth3P_Primavera-atm_r1i1p1f1_gr_195001-195001.nc 
 time = 15.5 ;
`````

Should the time_bnds be arranged when yearly concatation is performed in something as `0,365`? Or should the original files have a `0,365` time_bnds? 
Thanks for any hint.

**Comment by jonseddon** [comment]
Hi Paolo,

The bounds should have the same units as time. I would expect the bounds to be something like (some of the values may be incorrect by 1 or 2):

```
$ ncdump  -v time_bnds ideal_file_195001-195012.nc
data:

 time_bnds =
  0, 31,
  31, 59,
  59, 90,
  90, 120,
  ...
```

The original file for January 1950 should have bounds of 0, 31 and February 1950 should be 31, 59. Are the bounds correct in the original file for February?

If you could upload the original unconcatenated files for 1950 in a tar.gz or zip file then I am happy to have a look at them.

Thanks,

Jon

**Comment by oloapinivad** [comment]
Hi Jon ,

actually the problem was in the reference time of the monthly files that was not correctly set, which affected the time_bnds. We solved this and now the validation run smoothly!
Thanks a lot for your help!
Cheers,
Paolo
